routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontend\NewsController;
use App\Http\Controllers\Backend\GalleryController;
use App\Http\Controllers\Backend\ArticlesController;
use App\Http\Controllers\Backend\SettingsController;
use App\Http\Controllers\Backend\CategoriesController;
use App\Http\Controllers\Backend\MessagesController;

Route::get('/', [NewsController::class, 'index'])->name('frontend.home');
Route::get('/about', [NewsController::class, 'about'])->name('frontend.about');
Route::get('/terms', [NewsController::class, 'terms'])->name('frontend.terms');
Route::get('/policies', [NewsController::class, 'policies'])->name('frontend.policies');
Route::get('/gallery', [NewsController::class, 'gallery'])->name('frontend.gallery');
Route::get('/contact', [NewsController::class, 'contact'])->name('frontend.contact');
Route::get('/{category}/show', [NewsController::class, 'getNewsByCategory'])->name('frontend.categories');
Route::post('/contact/submit-form', [NewsController::class, 'submitForm'])->name('frontend.submit-form');
Route::get('/article/{article}/show', [NewsController::class, 'showArticle'])->name('frontend.articles');
Route::get('/search', [NewsController::class, 'search'])->name('frontend.search');

Route::group(['middleware' => ['auth'], 'prefix' => 'backend'], function () {

    Route::get('/dashboard', function () { return view('backend.dashboard'); })->name('backend.dashboard');

    // Articles routes
    Route::get('/articles', [ArticlesController::class, 'index'])->name('backend.articles');
    Route::get('/articles/trashed', [ArticlesController::class, 'getTrashed'])->name('backend.articles.trashed');
    Route::get('/articles/create', [ArticlesController::class, 'create'])->name('backend.articles.create');
    Route::post('/articles/store', [ArticlesController::class, 'store'])->name('backend.articles.store');
    Route::get('/articles/{article}/show', [ArticlesController::class, 'show'])->name('backend.articles.show');
    Route::get('/articles/{article}/restore', [ArticlesController::class, 'restore'])->name('backend.articles.restore');
    Route::get('/articles/{article}/edit', [ArticlesController::class, 'edit'])->name('backend.articles.edit');
    Route::patch('/articles/{article}/update', [ArticlesController::class, 'update'])->name('backend.articles.update');
    Route::get('/articles/{article}/trash', [ArticlesController::class, 'trash'])->name('backend.articles.trash');
    Route::get('/articles/{article}/delete', [ArticlesController::class, 'delete'])->name('backend.articles.delete');
    Route::get('/articles/delete-all', [ArticlesController::class, 'deleteAll'])->name('backend.articles.delete-all');
    Route::get('/articles/trash-all', [ArticlesController::class, 'trashAll'])->name('backend.articles.trash-all');
    Route::get('/articles/restore-all', [ArticlesController::class, 'restoreAll'])->name('backend.articles.restore-all');

    // Categories routes
    Route::get('/categories', [CategoriesController::class, 'index'])->name('backend.categories');
    Route::get('/categories/trashed', [CategoriesController::class, 'getTrashed'])->name('backend.categories.trashed');
    Route::get('/categories/create', [CategoriesController::class, 'create'])->name('backend.categories.create');
    Route::post('/categories/store', [CategoriesController::class, 'store'])->name('backend.categories.store');
    Route::get('/categories/{category}/show', [CategoriesController::class, 'show'])->name('backend.categories.show');
    Route::get('/categories/{category}/restore', [CategoriesController::class, 'restore'])->name('backend.categories.restore');
    Route::get('/categories/{category}/edit', [CategoriesController::class, 'edit'])->name('backend.categories.edit');
    Route::patch('/categories/{category}/update', [CategoriesController::class, 'update'])->name('backend.categories.update');
    Route::get('/categories/{category}/trash', [CategoriesController::class, 'trash'])->name('backend.categories.trash');
    Route::get('/categories/{category}/delete', [CategoriesController::class, 'delete'])->name('backend.categories.delete');

    // Setting Routes
    Route::get('/about', [SettingsController::class, 'about'])->name('backend.settings.about');
    Route::patch('/about/{about}/update', [SettingsController::class, 'updateAbout'])->name('backend.settings.about-update');
    Route::get('/password', [SettingsController::class, 'password'])->name('backend.settings.password');
    Route::patch('/password/update', [SettingsController::class, 'updatePassword'])->name('backend.settings.password-update');
    Route::get('/profile', [SettingsController::class, 'profile'])->name('backend.settings.profile');
    Route::patch('/profile/update', [SettingsController::class, 'updateProfile'])->name('backend.settings.profile-update');

    // Gallery Routes
    Route::get('/gallery', [GalleryController::class, 'index'])->name('backend.gallery');
    Route::get('/gallery/manage', [GalleryController::class, 'manage'])->name('backend.gallery.manage');
    Route::get('/gallery/create', [GalleryController::class, 'create'])->name('backend.gallery.create');
    Route::get('/gallery/{id}/edit', [GalleryController::class, 'edit'])->name('backend.gallery.edit');
    Route::patch('/gallery/{id}/update', [GalleryController::class, 'update'])->name('backend.gallery.update');
    Route::post('/gallery/store', [GalleryController::class, 'store'])->name('backend.gallery.store');
    Route::get('/gallery/{id}/delete', [GalleryController::class, 'destroy'])->name('backend.gallery.destroy');


    // Messages Routes
    Route::get('/messages', [MessagesController::class, 'index'])->name('backend.messages');
    Route::get('/messages/show/{id}', [MessagesController::class, 'show'])->name('backend.messages.show');
    Route::get('/messages/destroy/{id}', [MessagesController::class, 'destroy'])->name('backend.messages.destroy');
});

Route::fallback(function () {
    return view("errors.404");
});
require __DIR__.'/auth.php';

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Spatie\Searchable\Searchable;
use Illuminate\Support\Facades\DB;
use Spatie\Searchable\SearchResult;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;


class Article extends Model implements Searchable
{
    use HasFactory;

    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
        'title',
		'content',
		'slug',
        'image',
        'video_url',
        'category_id',
        'is_featured',
        'is_trending',
        'views'
    ];

    // Use Slug instead of ID
    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getFeaturedOrTrending($value)
    {
        if($value) {
            $value = 1;
            return $value;
        } else {
            $value = 0;
            return $value;
        }
    }

    public function incrementViewsCount($article) {
        DB::table('articles')->whereId($article->id)->increment('views');
    }


    public function getViewsAttribute($value)
    {
        if($value > 500){
            $views = [
                'number_of_views' => $value,
                'views_status' => 'Most Viewed'
            ];
        } elseif ($value > 200) {
            $views = [
                'number_of_views' => $value,
                'views_status' => 'Average Viewed'
            ];
        } else {
            $views = [
                'number_of_views' => $value,
                'views_status' => 'Normal Viewed'
            ];
        }
        return $views;
    }


    public function getCreatedAtAttribute($value) {
        $timestamp = strtotime($value);
        //Uppercase letters gives day, month in language(Jan, Third, etc)
        $year = date('Y', $timestamp);
        $month = date('M', $timestamp);
        //lowercase letters gives day, month in numbers(1, 3, etc)
        $day = date('d', $timestamp);

        $date = [
            'year' => $year,
            'month' => $month,
            'day'   => $day
        ];
        return $date;
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getSearchResult(): SearchResult
    {
        $url = route('frontend.articles', $this->slug);

        return new SearchResult(
            $this,
            Str::limit($this->title, 250),
            $url
         );
    }
}

app/Http/Controllers/Frontend/NewsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\Article;
use App\Models\Gallery;
use App\Models\Message;
use App\Models\Category;
use Illuminate\Http\Request;
use Spatie\Searchable\Search;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;

class NewsController extends Controller
{
    public function index() 
    {
        $home_articles = Article::latest()->where('is_featured', 1)->paginate(8);
        $top_articles = Article::latest()->inRandomOrder()->limit(5)->where('is_featured', 1)->get();
        $site_title = "Atom Articles - Home";
        return view('frontend.pages.index', compact('home_articles', 'top_articles', 'site_title'));
    }

    public function about()
    {
        $site_title = "Atom Articles - About Us";
        return view('frontend.pages.about', compact('site_title'));
    }

    public function terms()
    {
        $site_title = "Atom Articles - Terms & Conditions";
        return view('frontend.pages.terms', compact('site_title'));
    }

   public function policies()
    {
        $site_title = "Atom Articles - Privacy Policies";
        return view('frontend.pages.policies', compact('site_title'));
    }


    public function contact()
    {
        $site_title = "Atom Articles - Contact Us";
        return view('frontend.pages.contact', compact('site_title'));
    }

    public function submitForm(Request $request)
    {
    //    dd($request->all());
       $this -> validate($request, [
            'name'   => 'required',
            'phone'  => 'required',
            'message' => 'required'
       ]);

       $input = $request->only(['name', 'email', 'phone', 'message']);

       $result = Message::create($input);

      \Mail::send('mail', array(
            'name' => $request->get('name'),
            'email' => $request->get('phone'),
            'phone' => $request->get('enail'),
            'message' => $request->get('message'),
        ), function($message) use ($request){
            $message->from($request->email);
            $message->to('admin@atomarticles.com', 'Hello Admin')->subject($request->get('subject'));
        });    

       if($result) {
            session()->flash('success', 'Message sent Successfully!');
        } else {
            session()->flash('error', 'Something went wrong.');
        }

        return redirect() -> route('frontend.contact');
    }

    public function getNewsByCategory($category)
    {
        $category = Category::where('slug', $category)->first();
        $category_articles = Article::where('category_id', $category->id)->paginate(6);
        $site_title = "Atom Articles - " .$category->name;

        return view('frontend.pages.categories', compact('category_articles', 'category', 'site_title'));
    }

    public function showArticle(Article $article)
    {
        $article->incrementViewsCount($article);
        // dd($article);
        $site_title = "Atom Articles - " .$article->title;

        return view('frontend.pages.show-article', compact('site_title'))->with('full_article', $article);
    }

    public function gallery()
    {
        $gallery = Gallery::latest()->paginate(20);
        $site_title = "Atom Articles - Gallery";

        return view('frontend.pages.gallery', compact('gallery', 'site_title'));
    }

    public function search(Request $request)
    {
        $q = $request->input('query');
        $site_title = "Atom Articles - Search";
         $searchResults = (new Search())
            ->registerModel(Category::class, 'name')
            ->registerModel(Article::class, ['title', 'content'])
            ->limitAspectResults(200)
            ->perform($q);
        return view('frontend.pages.search', compact('searchResults', 'site_title'));
    }
}

resources/views/frontend/pages/categories.blade.php
@extends('frontend.layouts.app')

@section('main-content')

<!--Sidebar Page Container-->
<div class="sidebar-page-container">
    <div class="auto-container">
        <div class="row clearfix">

            <!--Content Side-->
            <div class="content-side col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <!--Latest News-->
                <div class="latest-news-section">
                    <!--Sec Title-->
                    <div class="sec-title">
                        <h2>{{ $category->name }}</h2>
                    </div>
                    <div class="row clearfix">

                        <!--News Block Two-->
                        @foreach($category_articles as $article)
                        <div class="news-block-two with-margin col-md-6 col-sm-6 col-xs-12">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="{{ route('frontend.articles', $article) }}"><img class="wow fadeIn" data-wow-delay="0ms" data-wow-duration="2500ms" src="{{ asset(imagePath($article->image, 'articles')) }}" alt="" style="width:381px;height:293px;" /></a>

                                    <div class="category"><a href="#">{{ $article->category->name }}</a></div>
                                </div>
                                <div class="lower-box">
                                    <h3><a href="{{ route('frontend.articles', $article) }}">{{ $article->title }}</a></h3>

                                    <ul class="post-meta">
                                        <li><span class="icon fa fa-clock-o"></span>{{ $article->created_at['month'] .' '. $article->created_at['day'] }}, {{ $article->created_at['year'] }}</li>

                                        <li><span class="icon fa fa-eye"></span>{{ $article->views['number_of_views'] ?? '0' }}</li>
                                    </ul>
                                    <div class="text">{{ Str::limit($article->content, 200, '...') }}
                                    </div>
                                    <a href="{{ route('frontend.articles', $article) }}" class="btn btn-danger btn-sm mt-4" style="margin-top:10px;">Read More</a>

                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>

                    <!-- Styled Pagination -->
                    <div class="pagination-custom">
                        {{ $category_articles->links() }}
                    </div>

                </div>
            </div>

            <!--Sidebar Side-->
            <div class="sidebar-side col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <aside class="sidebar default-sidebar right-sidebar">
                    <div class="sidebar-widget search-box">
                        	<form method="get" action="{{ route('frontend.search') }}">
                                <div class="form-group">
                                    <input type="search" name="query" value="" placeholder="Search" required="">
                                    <button type="submit"><span class="icon fa fa-search"></span></button>
                                </div>
                            </form>
						</div>
                    <!--Social Widget-->
                    <div class="sidebar-widget sidebar-social-widget">
                        <div class="sidebar-title">
                            <h2>Follow Us</h2>
                        </div>
                        <ul class="social-icon-one alternate">
                            <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                            <li class="twitter"><a href="#"><span class="fa fa-twitter"></span></a></li>
                            <li class="instagram"><a href="#"><span class="fa fa-instagram"></span></a></li>
                        </ul>
                    </div>
                    <!--End Social Widget-->


                    <!--Category Widget-->
                    <div class="sidebar-widget categories-widget">
                        <div class="sidebar-title">
                            <h2>Categories</h2>
                        </div>
                        <ul class="cat-list">
                            @foreach($side_categories as $category)
                            @if ($category->articles->count() > 0) 
                            <li class="clearfix"><a href="{{ route('frontend.categories', $category) }}">{{ $category->name }} <span>({{ $category->articles->count() ?? 0 }})</span></a></li>
                            @endif

                            @endforeach
                        </ul>
                    </div>
                    <!--End Category Widget-->

                    <!--News Post Widget-->
                    <div class="sidebar-widget posts-widget">

                        <!--Product widget Tabs-->
                        <div class="product-widget-tabs">
                            <!--Product Tabs-->
                            <div class="prod-tabs tabs-box">

                                <!--Tab Btns-->
                                <ul class="tab-btns tab-buttons clearfix">
                                    <li data-tab="#prod-popular" class="tab-btn active-btn">Featured</li>

                                </ul>

                                <!--Tabs Container-->
                                <div class="tabs-content">

                                    <!--Tab / Active Tab-->
                                    <div class="tab active-tab" id="prod-popular">
                                        <div class="content">
                                            @foreach($popular_articles as $article)
                                            <article class="widget-post">
                                                <figure class="post-thumb"><a href="{{ route('frontend.articles', $article) }}"><img class="wow fadeIn" data-wow-delay="0ms" data-wow-duration="2500ms" src="{{ asset(imagePath($article->image, 'articles')) }}" style="width:86;height:79px;" alt=""></a>

                                                     <div class="overlay"></div>
                                                </figure>
                                                <div class="text"><a href="{{ route('frontend.articles', $article) }}">{{ Str::limit($article->title, 70, '..') }}</a></div>

                                                <div class="post-info">{{ $article->created_at['month'] .' '. $article->created_at['day'] }}, {{ $article->created_at['year'] }}</div>
                                            </article>
                                            @endforeach

                                        </div>
                                    </div>

                                </div>

                            </div>

                        </div>
                        <!--End Product Info Tabs-->

                    </div>
                    <!--End Post Widget-->


            </div>

        </div>

    </div>
</div>
<!--End Sidebar Page Container-->
@endsection

resources/views/frontend/pages/index.blade.php
@extends('frontend.layouts.app')
@section('main-content')

   <!--Sidebar Page Container-->
   <div class="sidebar-page-container">
       <div class="auto-container">
           <div class="row clearfix">

               <!--Content Side-->
               <div class="content-side col-lg-8 col-md-8 col-sm-12 col-xs-12">
                   <!--Latest News-->
                   <div class="latest-news-section">
                       <!--Sec Title-->
                       <div class="sec-title">
                           <h2>Latest News</h2>
                       </div>
                       <div class="row clearfix">

                           <!--News Block Two-->
                           @foreach($home_articles as $article)
                           <div class="news-block-two with-margin col-md-4 col-sm-6 col-xs-12">
                               <div class="inner-box">
                                   <div class="image">
                                       <a href="{{ route('frontend.articles', $article) }}"><img class="wow fadeIn" data-wow-delay="0ms" data-wow-duration="2500ms" src="{{ asset(imagePath($article->image, 'articles')) }}" alt="" style="width:300px;height:200px;" /></a>

                                       <div class="category"><a href="#">{{ $article->category->name }}</a></div>
                                   </div>
                                   <h4><a href="{{ route('frontend.articles', $article) }}">{{ $article->title }}</a></h4>
                                   
                                   <div class="lower-box" style="padding: 0px;">
                                       <ul class="post-meta">
                                           <li><span class="icon fa fa-clock-o"></span>{{ $article->created_at['month'] .' '. $article->created_at['day'] }}, {{ $article->created_at['year'] }}</li>

                                           <li><span class="icon fa fa-eye"></span>{{ $article->views['number_of_views'] ?? '0' }}</li>
                                       </ul>
                                       <div class="text">{!! Str::limit($article->content, 90, '...') !!}
                                       </div>
                                       <a href="{{ route('frontend.articles', $article) }}" class="btn btn-danger btn-sm mt-4" style="margin-top:10px;">Read More</a>

                                   </div>
                               </div>
                           </div>
                           @endforeach
                       </div>

                       <!-- Styled Pagination -->
                       <div class="pagination-custom">
                           {{ $home_articles->links() }}
                       </div>

                   </div>
               </div>

               <!--Sidebar Side-->
               <div class="sidebar-side col-lg-4 col-md-4 col-sm-12 col-xs-12">
                   <aside class="sidebar default-sidebar right-sidebar">
                    <div class="sidebar-widget search-box">
                        	<form method="get" action="{{ route('frontend.search') }}">
                                <div class="form-group">
                                    <input type="search" name="query" value="" placeholder="Search" required="">
                                    <button type="submit"><span class="icon fa fa-search"></span></button>
                                </div>
                            </form>
						</div>
                       <!--Social Widget-->
                       <div class="sidebar-widget sidebar-social-widget">
                           <div class="sidebar-title">
                               <h2>Follow Us</h2>
                           </div>
                           <ul class="social-icon-one alternate">
                               <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                               <li class="twitter"><a href="#"><span class="fa fa-twitter"></span></a></li>
                               <li class="instagram"><a href="#"><span class="fa fa-instagram"></span></a></li>
                           </ul>
                       </div>
                       <!--End Social Widget-->


                       <!--Category Widget-->
                       <div class="sidebar-widget categories-widget">
                           <div class="sidebar-title">
                               <h2>Categories</h2>
                           </div>
                           <ul class="cat-list">
                                @foreach($side_categories as $category)
                                @if($category->articles->count() > 0)
                                    <li class="clearfix"><a href="{{ route('frontend.categories', $category) }}">{{ $category->name }} <span>({{ $category->articles->count() ?? 0 }})</span></a></li>
                                @endif
                                @endforeach
                           </ul>
                       </div>
                       <!--End Category Widget-->

                       <!--News Post Widget-->
                       <div class="sidebar-widget posts-widget">

                           <!--Product widget Tabs-->
                           <div class="product-widget-tabs">
                               <!--Product Tabs-->
                               <div class="prod-tabs tabs-box">

                                   <!--Tab Btns-->
                                   <ul class="tab-btns tab-buttons clearfix">
                                       <li data-tab="#prod-popular" class="tab-btn active-btn">Trending</li>
        
                                   </ul>

                                   <!--Tabs Container-->
                                   <div class="tabs-content">

                                       <!--Tab / Active Tab-->
                                       <div class="tab active-tab" id="prod-popular">
                                           <div class="content">
                                              @foreach($trending_articles as $article)
                                               <article class="widget-post">
                                                   <figure class="post-thumb"><a href="{{ route('frontend.categories', $category) }}"><img class="wow fadeIn" data-wow-delay="0ms" data-wow-duration="2500ms" src="{{ asset(imagePath($article->image, 'articles')) }}" style="width:86;height:79px;" alt=""></a>
                                                       <div class="overlay"></div>
                                                   </figure>
                                                   <div class="text"><a href="{{ route('frontend.categories', $category) }}">{{ Str::limit($article->title, 70, '..') }}</a></div>
                                                   <div class="post-info">{{ $article->created_at['month'] .' '. $article->created_at['day'] }}, {{ $article->created_at['year'] }}</div>
                                               </article>
                                                @endforeach

                                           </div>
                                       </div>

                                   </div>

                               </div>

                           </div>
                           <!--End Product Info Tabs-->

                       </div>
                       <!--End Post Widget-->

                      
               </div>

           </div>

       </div>
   </div>
   <!--End Sidebar Page Container-->
@endsection

resources/views/frontend/pages/show-article.blade.php
@extends('frontend.layouts.app')

@section('main-content')
    <!--Blog Single Gallery-->
    <div class="blog-single-gallery grey-bg">
        <div class="auto-container">
            <div class="image">
                <img src="{{ asset(imagePath($full_article->image, 'articles')) }}" alt="" />
            </div>
        </div>
    </div>
    <!--End Single Gallery-->

 
    <!--Sidebar Page Container-->
    <div class="sidebar-page-container">
        <div class="auto-container">
            <div class="row clearfix">

                <!--Content Side-->
                <div class="content-side col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="content">
                        <div class="blog-single">
                            <div class="inner-box">
                                <div class="upper-box">
                                    <ul class="breadcrumb-bar">
                                        <li><a href="{{ route('frontend.home') }}">Home</a></li>
                                        <li>{{ $full_article->category->name }}</li>
                                        <li>{{ $full_article->title }}</li>
                                    </ul>
                                    <ul class="tag-title">
                                        <li>{{ $full_article->is_featured ? 'Featured' : '' }}</li>
                                        <li>{{ $full_article->category->name }}</li>

                                    </ul>
                                    <h2>{{ $full_article->title }}</h2>
                                    <ul class="post-meta">
                                        <li><span class="icon qb-clock"></span>{{ $full_article->created_at['month'] }} {{ $full_article->created_at['day'] }}, {{ $full_article->created_at['year'] }}</li>


                                        <li><span class="icon qb-user2"></span>by Admin</li>
                                        <li><span class="icon qb-eye"></span>{{ $full_article->views['number_of_views'] ?? '0' }} Views</li>
                                    </ul>
                                    <ul class="social-icon-one alternate">
                                        <li class="share">Share:</li>
                                        <li><a href="{{ $about->facebook }}"><span class="fa fa-facebook"></span></a></li>
                                        <li class="twitter"><a href="#"><span class="fa fa-twitter"></span></a></li>
                                        <li class="g_plus"><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                    </ul>
                                </div>

                                <div class="text">
                                    {!! $full_article->content !!}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

             
            </div>

        </div>
    </div>
    <!--End Sidebar Page Container-->

@endsection

@section('footerelements')

@endsection